In [2]:
#Guilherme Mendes de Oliveira
#2018 046939

In [3]:
import io
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
# Import  dos dados - Uma Vez somente
f = io.open('despesas_publicas_tp1.sql','r')
sql = f.read()
cursor.executescript(sql)

NameError: name 'cursor' is not defined

In [ ]:
#Criando a Conexão do Banco

In [5]:
conn = sqlite3.connect('despesas_publicas_tp1')
cursor = conn.cursor()

In [ ]:
#Consulta 1
#Liste todos os codigos e nomes de funcoes da subfuncao que possui o maior numero de funcoes.

In [6]:
df = pd.read_sql_query("SELECT * FROM FUNCAO WHERE COD_FUNCAO IN "
+"(SELECT COD_FUNCAO FROM DETALHAMENTO_FUNCAO WHERE COD_SUBFUNCAO = "
+"(SELECT COD_SUBFUNCAO FROM DETALHAMENTO_FUNCAO GROUP BY COD_SUBFUNCAO ORDER BY COUNT(*) DESC ))"
+"ORDER BY COD_FUNCAO",conn)

In [7]:
df

   COD_FUNCAO        NOME_FUNCAO
0           5    Defesa nacional
1           6  Segurança pública
2          26         Transporte

In [8]:
#Consulta 5
#Liste o codigo e nome dos orgaos que possuiram os 5 maiores valores de despesas totais
#nas funcoes de educacao e saude durante o ano de 2018.

In [9]:
df = pd.read_sql_query("SELECT COD_ORGAO, NOME_ORGAO FROM ORGAO NATURAL JOIN"
+"(SELECT COD_ORGAO, SUM(VALOR_DESPESA) FROM DESPESA_PUBLICA NATURAL JOIN DETALHAMENTO_FUNCAO WHERE COD_FUNCAO IN "
+"(SELECT COD_FUNCAO FROM FUNCAO WHERE NOME_FUNCAO IN ('Educação', 'Saúde'))" 
+" AND ANO_DESPESA = 2018 GROUP BY COD_ORGAO ORDER BY SUM(VALOR_DESPESA) DESC)",conn)
df

   COD_ORGAO                                     NOME_ORGAO
0      52000                           Ministério da Defesa
1      26000                         Ministério da Educação
2      36000                            Ministério da Saúde
3      24000  Ministério da Ciência, Tecnologia, Inovações
4      30000      Ministério da Justiça e Segurança Pública

In [ ]:
#Consulta 7
#Liste os programas de governo e a quantidade de orgaos governamentais distintos envolvidos
#nas despesas publicas desses programas. Nesta consulta, desconsidere valores
#de despesa negativos ou iguais a zero no perIodo.

In [63]:
df = pd.read_sql_query("SELECT DISTINCT NOME_PROGRAMA_GOVERNO, COUNT(COD_ORGAO) AS QNT_ORGAO FROM "
+"DESPESA_PUBLICA NATURAL JOIN PROGRAMA_GOVERNO WHERE VALOR_DESPESA > 0 GROUP BY COD_ORGAO "
+"ORDER BY QNT_ORGAO DESC",conn)
df

     NOME_PROGRAMA_GOVERNO  QNT_ORGAO
0             MAIS MEDICOS         10
1  REGULARIZACAO FUNDIARIA          4
2             MAIS MEDICOS          3
3       BRASIL SEM MISERIA          2

In [ ]:
#Consulta 10
#Liste todas as despesas publicas (codigo da despesa, mes e ano da despesa, modalidade,valor), 
#ordenadas de forma decrescente pelo valor, em que o programa de governo eH aquele que possui 
#o maior valor total em despesas durante o ano de 2018.

In [91]:
df = pd.read_sql_query("SELECT NOME_PROGRAMA_GOVERNO, COD_DESPESA, MES_DESPESA, ANO_DESPESA, MODALIDADE_DESPESA, "
+"VALOR_DESPESA FROM DESPESA_PUBLICA NATURAL JOIN PROGRAMA_GOVERNO WHERE ANO_DESPESA = 2018 ORDER BY VALOR_DESPESA DESC",conn)
df

,NOME_PROGRAMA_GOVERNO,COD_DESPESA,MES_DESPESA,ANO_DESPESA,MODALIDADE_DESPESA,VALOR_DESPESA
0,ENEM,835,9,2018,Reserva de Contingência,334126.70
1,BRASIL SEM MISERIA,1013,4,2018,TRANSFERENCIAS A MUNICIPIOS - FUNDO A FUNDO,219668.07
2,BRASIL SEM MISERIA,60,11,2018,Reserva de Contingência,81120.13
3,BRASIL SEM MISERIA,973,3,2018,Reserva de Contingência,58918.28
4,CONTROLE DO CANCER,705,2,2018,Reserva de Contingência,38971.19
5,PRONATEC,357,5,2018,Reserva de Contingência,28073.08
6,BRASIL SEM MISERIA,858,10,2018,Reserva de Contingência,19250.00
7,PRONATEC,356,4,2018,Reserva de Contingência,18178.00
8,MAIS MEDICOS,785,7,2018,Reserva de Contingência,11000.00
9,BRASIL SEM MISERIA,28,2,2018,Reserva de Contingência,8215.70
10,PRONATEC,364,12,2018,Reserva de Contingência,5900.00
11,PRONATEC,341,1,2018,APLICACOES DIRETAS - OPER.INTRA-ORCAMENTARIAS,5000.00
12,MAIS MEDICOS,485,8,2018,Reserva de Contingência,2400.00
13,PRONATEC,353,1,2018,Reserva de Contingência,2000.00
14,REGULARIZACAO FUNDIARIA,105,7,2018,Reserva de Contingência,1497.26
15,REDE CEGONHA,240,1,2018,Reserva de Contingência,1210.00
16,MAIS MEDICOS,788,10,2018,Reserva de Contingência,1000.00
17,PRONATEC,348,8,2018,APLICACOES DIRETAS - OPER.INTRA-ORCAMENTARIAS,726.00
18,PRONATEC,362,10,2018,Reserva de Contingência,385.38
19,ENEM,300,6,2018,Reserva de Contingência,135.36
20,BRASIL SEM MISERIA,58,9,2018,Reserva de Contingência,3.42
21,BRASIL SEM MISERIA,0,11,2018,Reserva de Contingência,0.00
22,BRASIL SEM MISERIA,1,11,2018,Reserva de Contingência,0.00
23,BRASIL SEM MISERIA,2,12,2018,Reserva de Contingência,0.00
24,BRASIL SEM MISERIA,3,3,2018,Reserva de Contingência,0.00
25,BRASIL SEM MISERIA,4,4,2018,Reserva de Contingência,0.00
26,BRASIL SEM MISERIA,5,5,2018,Reserva de Contingência,0.00
27,BRASIL SEM MISERIA,6,7,2018,Reserva de Contingência,0.00
28,BRASIL SEM MISERIA,7,11,2018,Reserva de Contingência,0.00
29,VIOLENCIA NO TRANSITO,8,10,2018,Reserva de Contingência,0.00
...,...,...,...,...,...,...
1097,BRASIL SEM MISERIA,1097,3,2018,Transferências a Estados e ao Distrito Federal,0.00
1098,BRASIL SEM MISERIA,1098,5,2018,Transferências a Estados e ao Distrito Federal,0.00
1099,BRASIL SEM MISERIA,1099,6,2018,Transferências a Estados e ao Distrito Federal,0.00
1100,BRASIL SEM MISERIA,1100,7,2018,Transferências a Estados e ao Distrito Federal,0.00
1101,BRASIL SEM MISERIA,1101,8,2018,Transferências a Estados e ao Distrito Federal,0.00
1102,BRASIL SEM MISERIA,1102,9,2018,Transferências a Estados e ao Distrito Federal,0.00
1103,BRASIL SEM MISERIA,1103,10,2018,Transferências a Estados e ao Distrito Federal,0.00
1104,BRASIL SEM MISERIA,1104,12,2018,Transferências a Estados e ao Distrito Federal,0.00
1105,BRASIL SEM MISERIA,1105,1,2018,Transferências a Instituições Privadas sem Fin...,0.00
1106,BRASIL SEM MISERIA,1106,2,2018,Transferências a Instituições Privadas sem Fin...,0.00
1107,BRASIL SEM MISERIA,1107,3,2018,Transferências a Instituições Privadas sem Fin...,0.00
1108,BRASIL SEM MISERIA,1108,5,2018,Transferências a Instituições Privadas sem Fin...,0.00
1109,BRASIL SEM MISERIA,1109,6,2018,Transferências a Instituições Privadas sem Fin...,0.00
1110,BRASIL SEM MISERIA,1110,7,2018,Transferências a Instituições Privadas sem Fin...,0.00
1111,BRASIL SEM MISERIA,1111,8,2018,Transferências a Instituições Privadas sem Fin...,0.00
1112,BRASIL SEM MISERIA,1112,10,2018,Transferências a Instituições Privadas sem Fin...,0.00
1113,BRASIL SEM MISERIA,1113,12,2018,Transferências a Instituições Privadas sem Fin...,0.00
1114,BRASIL SEM MISERIA,1114,1,2018,Reserva de Contingência,0.00
1115,BRASIL SEM MISERIA,1115,2,2018,Reserva de Contingência,0.00
1116,BRASIL SEM MISERIA,1116,3,2018,Reserva de Contingência,0.00
1117,BRASIL SEM MISERIA,1117,4,2018,Reserva de Contingência,0.00
1118,BRASIL SEM MISERIA,1118,5,2018,Reserva de Contingência,0.00
1119,BRASIL SEM MISERIA,1119,6,2018,Reserva de Contingência,0.00
1120,BRASIL SEM MISERIA,1120,7,2018,Reserva de Contingência,0.00
1121,BRASIL SEM MISERIA,1121,8,2018,Reserva de Contingência,0.00
1122,BRASIL SEM MISERIA,1122,9,2018,Reserva de Contingência,0.00
1123,BRASIL SEM MISERIA,1123,10,2018,Reserva de Contingência,0.00
1124,BRASIL SEM MISERIA,1124,11,2018,Reserva de Contingência,0.00
1125,BRASIL SEM MISERIA,1125,12,2018,Reserva de Contingência,0.00
1126,BRASIL SEM MISERIA,1126,5,2018,Reserva de Contingência,0.00

In [ ]:
#Consulta 4
#Liste o mes e ano, modalidade, programa de governo e valor de todas as despesas do
#orgao Ministerio da Educacao no primeiro semestre de 2018.

In [68]:
df = pd.read_sql_query("SELECT MES_DESPESA, ANO_DESPESA, MODALIDADE_DESPESA,NOME_PROGRAMA_GOVERNO, "
+"VALOR_DESPESA FROM DESPESA_PUBLICA NATURAL JOIN PROGRAMA_GOVERNO WHERE COD_ORGAO = "
+"(SELECT COD_ORGAO FROM ORGAO WHERE NOME_ORGAO = 'Ministério da Educação') AND MES_DESPESA <7",conn)
df

,MES_DESPESA,ANO_DESPESA,MODALIDADE_DESPESA,NOME_PROGRAMA_GOVERNO,VALOR_DESPESA
0,1,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
1,2,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
2,3,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
3,4,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
4,5,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
5,6,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
6,1,2018,APLICACOES DIRETAS - OPER.INTRA-ORCAMENTARIAS,VIVER SEM LIMITE,0.0
7,6,2018,APLICACOES DIRETAS - OPER.INTRA-ORCAMENTARIAS,VIVER SEM LIMITE,0.0
8,1,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
9,2,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
10,3,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
11,4,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
12,5,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
13,6,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
14,2,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
15,5,2018,Transferências a Estados e ao Distrito Federal,VIVER SEM LIMITE,0.0
16,5,2018,Transferências a Municípios,VIVER SEM LIMITE,0.0
17,2,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
18,3,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
19,6,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
20,5,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
21,1,2018,Reserva de Contingência,MELHOR EM CASA,0.0
22,2,2018,Reserva de Contingência,MELHOR EM CASA,0.0
23,1,2018,Reserva de Contingência,REDE CEGONHA,1210.0
24,2,2018,Reserva de Contingência,REDE CEGONHA,0.0
25,3,2018,Reserva de Contingência,REDE CEGONHA,0.0
26,4,2018,Reserva de Contingência,REDE CEGONHA,0.0
27,5,2018,Reserva de Contingência,REDE CEGONHA,0.0
28,6,2018,Reserva de Contingência,REDE CEGONHA,0.0
29,1,2018,APLICACOES DIRETAS - OPER.INTRA-ORCAMENTARIAS,CONTROLE DO CANCER,0.0
...,...,...,...,...,...
123,2,2018,Reserva de Contingência,BRASIL SEM MISERIA,0.0
124,3,2018,Reserva de Contingência,BRASIL SEM MISERIA,0.0
125,4,2018,Reserva de Contingência,BRASIL SEM MISERIA,0.0
126,5,2018,Reserva de Contingência,BRASIL SEM MISERIA,0.0
127,1,2018,Reserva de Contingência,BRASIL SEM MISERIA,0.0
128,3,2018,Reserva de Contingência,BRASIL SEM MISERIA,0.0
129,4,2018,Reserva de Contingência,BRASIL SEM MISERIA,0.0
130,5,2018,Reserva de Contingência,BRASIL SEM MISERIA,0.0
131,6,2018,Reserva de Contingência,BRASIL SEM MISERIA,0.0
132,2,2018,Reserva de Contingência,REGULARIZACAO FUNDIARIA,0.0
133,1,2018,APLICACOES DIRETAS - OPER.INTRA-ORCAMENTARIAS,REGULARIZACAO FUNDIARIA,0.0
134,1,2018,Reserva de Contingência,REGULARIZACAO FUNDIARIA,0.0
135,1,2018,Reserva de Contingência,MAIS MEDICOS,0.0
136,2,2018,Reserva de Contingência,MAIS MEDICOS,0.0
137,3,2018,Reserva de Contingência,MAIS MEDICOS,0.0
138,4,2018,Reserva de Contingência,MAIS MEDICOS,0.0
139,5,2018,Reserva de Contingência,MAIS MEDICOS,0.0
140,6,2018,Reserva de Contingência,MAIS MEDICOS,0.0
141,1,2018,Reserva de Contingência,MAIS MEDICOS,0.0
142,2,2018,Reserva de Contingência,MAIS MEDICOS,0.0
143,3,2018,Reserva de Contingência,MAIS MEDICOS,0.0
144,4,2018,Reserva de Contingência,MAIS MEDICOS,0.0
145,5,2018,Reserva de Contingência,MAIS MEDICOS,0.0
146,6,2018,Reserva de Contingência,MAIS MEDICOS,0.0
147,1,2018,Reserva de Contingência,MAIS MEDICOS,0.0
148,2,2018,Reserva de Contingência,MAIS MEDICOS,0.0
149,3,2018,Reserva de Contingência,MAIS MEDICOS,0.0
150,4,2018,Reserva de Contingência,MAIS MEDICOS,0.0
151,5,2018,Reserva de Contingência,MAIS MEDICOS,0.0
152,6,2018,Reserva de Contingência,MAIS MEDICOS,0.0

In [ ]:
#Consulta 11 
#Liste os codigos e nomes dos orgaos governamentais relacionados ao programa de
#governo (ou programas, caso haja empate) que alcancou mais registros de despesas
#publicas durante o ano.

In [71]:
df = pd.read_sql_query("SELECT COD_ORGAO, NOME_ORGAO,COUNT(VALOR_DESPESA) AS NUM_DESPESAS, SUM(VALOR_DESPESA) "
+"AS TOTAL FROM (SELECT VALOR_DESPESA, COD_ORGAO, NOME_ORGAO FROM DESPESA_PUBLICA NATURAL JOIN ORGAO)GROUP BY "
+"COD_ORGAO ORDER BY NUM_DESPESAS DESC, TOTAL DESC",conn)
df

,COD_ORGAO,NOME_ORGAO,NUM_DESPESAS,TOTAL
0,26000,Ministério da Educação,294,64007.82
1,36000,Ministério da Saúde,219,50971.19
2,55000,Ministério do Desenvolvimento Social,197,278586.35
3,22000,"Ministério da Agricultura, Pecuária e Abastec",125,90836.51
4,30000,Ministério da Justiça e Segurança Pública,91,0.00
5,52000,Ministério da Defesa,56,353376.70
6,24000,"Ministério da Ciência, Tecnologia, Inovações",48,0.00
7,53000,Ministério da Integração Nacional,46,0.00
8,44000,Ministério do Meio Ambiente,14,0.00
9,25000,Ministério da Fazenda,13,0.00
10,39000,"Ministério dos Transportes, Portos e Aviação",12,0.00
11,20000,Presidência da República,10,0.00
12,35000,Ministério das Relações Exteriores,1,0.00
13,81000,Ministério dos Direitos Humanos,1,0.00

In [ ]:
#### Tradução Algebra

In [ ]:
#CONSULTA 12

In [99]:
df = pd.read_sql_query("SELECT DISTINCT NOME_FUNCAO, VALOR_DESPESA FROM FUNCAO "
+"NATURAL JOIN DETALHAMENTO_FUNCAO NATURAL JOIN DESPESA_PUBLICA", conn)
df

              NOME_FUNCAO  VALOR_DESPESA
0     Essencial à justiça           0.00
1         Defesa nacional           0.00
2       Segurança pública           0.00
3      Assistência social           0.00
4      Assistência social       58918.28
5      Assistência social        8215.70
6      Assistência social      219668.07
7      Assistência social           3.42
8      Assistência social       19250.00
9      Assistência social       81120.13
10                  Saúde           0.00
11                  Saúde        1000.00
12                  Saúde       11000.00
13                  Saúde        1210.00
14                  Saúde       38971.19
15               Trabalho           0.00
16               Educação           0.00
17               Educação         385.38
18               Educação         726.00
19               Educação        2000.00
20               Educação        5000.00
21               Educação        5900.00
22               Educação       18178.00
23               Educação       28073.08
24               Educação        2400.00
25               Educação         135.36
26               Educação      334126.70
27  Direitos da cidadania           0.00
28              Urbanismo           0.00
29       Gestão ambiental           0.00
30   Ciência e Tecnologia           0.00
31            Agricultura           0.00
32    Organização agrária           0.00
33    Organização agrária        1497.26
34              Indústria           0.00
35             Transporte           0.00
36     Encargos especiais           0.00

In [ ]:
#Consulta 13

In [98]:
df = pd.read_sql_query("SELECT DISTINCT MODALIDADE_DESPESA, VALOR_DESPESA, NOME_ORGAO "
+"FROM (ORGAO NATURAL JOIN (SELECT * FROM DESPESA_PUBLICA WHERE MODALIDADE_DESPESA = "
+"'Reserva de Contingência'));",conn)
df

,MODALIDADE_DESPESA,VALOR_DESPESA,NOME_ORGAO
0,Reserva de Contingência,0.00,Presidência da República
1,Reserva de Contingência,0.00,"Ministério da Agricultura, Pecuária e Abastec"
2,Reserva de Contingência,8215.70,"Ministério da Agricultura, Pecuária e Abastec"
3,Reserva de Contingência,3.42,"Ministério da Agricultura, Pecuária e Abastec"
4,Reserva de Contingência,81120.13,"Ministério da Agricultura, Pecuária e Abastec"
5,Reserva de Contingência,1497.26,"Ministério da Agricultura, Pecuária e Abastec"
6,Reserva de Contingência,0.00,"Ministério da Ciência, Tecnologia, Inovações"
7,Reserva de Contingência,0.00,Ministério da Fazenda
8,Reserva de Contingência,0.00,Ministério da Educação
9,Reserva de Contingência,1210.00,Ministério da Educação
10,Reserva de Contingência,135.36,Ministério da Educação
11,Reserva de Contingência,2000.00,Ministério da Educação
12,Reserva de Contingência,18178.00,Ministério da Educação
13,Reserva de Contingência,28073.08,Ministério da Educação
14,Reserva de Contingência,385.38,Ministério da Educação
15,Reserva de Contingência,5900.00,Ministério da Educação
16,Reserva de Contingência,2400.00,Ministério da Educação
17,Reserva de Contingência,0.00,Ministério da Justiça e Segurança Pública
18,Reserva de Contingência,0.00,Ministério das Relações Exteriores
19,Reserva de Contingência,0.00,Ministério da Saúde
20,Reserva de Contingência,38971.19,Ministério da Saúde
21,Reserva de Contingência,11000.00,Ministério da Saúde
22,Reserva de Contingência,1000.00,Ministério da Saúde
23,Reserva de Contingência,0.00,"Ministério dos Transportes, Portos e Aviação"
24,Reserva de Contingência,0.00,Ministério do Meio Ambiente
25,Reserva de Contingência,0.00,Ministério da Defesa
26,Reserva de Contingência,334126.70,Ministério da Defesa
27,Reserva de Contingência,19250.00,Ministério da Defesa
28,Reserva de Contingência,0.00,Ministério da Integração Nacional
29,Reserva de Contingência,0.00,Ministério do Desenvolvimento Social
30,Reserva de Contingência,58918.28,Ministério do Desenvolvimento Social
31,Reserva de Contingência,0.00,Ministério dos Direitos Humanos

In [ ]:
#CONSULTA 14

In [97]:
df = pd.read_sql_query("SELECT DISTINCT VALOR_DESPESA, NOME_PROGRAMA_GOVERNO FROM (DESPESA_PUBLICA NATURAL JOIN "
+"(SELECT * FROM PROGRAMA_GOVERNO WHERE NOME_PROGRAMA_GOVERNO = 'ENEM'))",conn)
df

   VALOR_DESPESA NOME_PROGRAMA_GOVERNO
0           0.00                  ENEM
1         135.36                  ENEM
2      334126.70                  ENEM

In [ ]:
#CONSULTA 15

In [96]:
df = pd.read_sql_query("SELECT DISTINCT NOME_PROGRAMA_GOVERNO, QTD_ORGAOS_SUBORDINADOS, VALOR_DESPESA "
+"FROM (DESPESA_PUBLICA NATURAL JOIN (SELECT * FROM ORGAO WHERE NOME_ORGAO = 'Ministério da Educação') "
+"NATURAL JOIN PROGRAMA_GOVERNO)",conn)
df

       NOME_PROGRAMA_GOVERNO  QTD_ORGAOS_SUBORDINADOS  VALOR_DESPESA
0           VIVER SEM LIMITE                      104           0.00
1             MELHOR EM CASA                      104           0.00
2               REDE CEGONHA                      104        1210.00
3               REDE CEGONHA                      104           0.00
4         CONTROLE DO CANCER                      104           0.00
5     CIENCIA SEM FRONTEIRAS                      104           0.00
6                       ENEM                      104           0.00
7                       ENEM                      104         135.36
8               PROVA BRASIL                      104           0.00
9                   PRONATEC                      104           0.00
10                  PRONATEC                      104        5000.00
11                  PRONATEC                      104         726.00
12                  PRONATEC                      104        2000.00
13                  PRONATEC                      104       18178.00
14                  PRONATEC                      104       28073.08
15                  PRONATEC                      104         385.38
16                  PRONATEC                      104        5900.00
17      GESTAO AEROPORTUARIA                      104           0.00
18        DESASTRES NATURAIS                      104           0.00
19          CADEIAS PUBLICAS                      104           0.00
20  TERRITORIOS DA CIDADANIA                      104           0.00
21  CRACK, E POSSIVEL VENCER                      104           0.00
22        BRASIL SEM MISERIA                      104           0.00
23   REGULARIZACAO FUNDIARIA                      104           0.00
24              MAIS MEDICOS                      104           0.00
25              MAIS MEDICOS                      104        2400.00